### ISSUE TITLE
error in dtex.hy

### ISSUE THREAD

**Issue by cal644** [zeta0134/pikmin-nds#28]
Compilation stops when trying to run dtex.hy, and prints the following error:
[lines 101 to 130 are printed] "HyTypeError: Unknown expression in 'try'".

Any idea on what this is? How can I fix it?

**Comment by zeta0134** [comment]
I'm not positive, but I remember running into that issue when using a version of Hy that is newer than 0.11.1. The docker build is supposed to fix that by pinning the Hy version. I'll test when I'm near a computer, can you tell me how your building the project?

**Comment by cal644** [comment]
I couldn't get the docker image to work, so I installed all of the dependencies manually. Then, when trying to build the game, the error popped up. I'm definitely using a newer version of Hy than 0.11.1, so that's probably where the issue lies.

I'll install the right version and try again, and will update this message afterwards.
Thanks for your help!
